---
- name: Listar instâncias EC2 e exibir dados básicos
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - amazon.aws

  vars:
    aws_region: "us-east-2"

  tasks:
    - name: Obter informações das instâncias EC2
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
      register: ec2_info

    - name: Exibir informações básicas das instâncias
      debug:
        var: ec2_info