---
- name: Run 'ls' command on a Linux server
  hosts: all
  become: no
  tasks:
    - name: Execute 'ls' command
      ansible.builtin.command: "ls -lah /"
      register: ls_output

    - name: Show command output
      debug:
        var: ls_output.stdout

    - name: Identificar Node de Execução
      debug:
        msg: "Este job está rodando no node: {{ lookup('env', 'HOSTNAME') }}"