---
- name: Launch a Job Template in Ansible Automation Controller
  hosts: localhost
  vars:
    job_template_name: Exec_Job_Template
    host_name:
  gather_facts: no
  tasks:
    - name: Launch Job Template
      ansible.controller.job_launch:
        job_template: "{{ job_template_name }}"
        extra_vars: "{{ extra_vars | default(omit) }}"
        limit: "{{ host_name | default(omit) }}"
      register: resultado_job

    - name: Exibir resultado da execução do job
      debug:
        var: resultado_job

    - name: Exibir ID do job lançado
      debug:
        msg: "Job ID lançado: {{ resultado_job.id }}"

    - name: Compartilhar status e ID com o workflow
      set_stats:
        data:
          job_status: "{{ resultado_job.status | default('indefinido') }}"
          job_id: "{{ resultado_job.id | default('sem_id') }}"
