---
- name: Launch Exec Template
  hosts: localhost
  gather_facts: no
  vars:
    job_template_name: Exec_Job_Template
    host_name:

  tasks:
    - name: Lançar o Job Template
      ansible.controller.job_launch:
        job_template: "{{ job_template_name }}"
        extra_vars: "{{ extra_vars | default(omit) }}"
        limit: "{{ host_name | default(omit) }}"
      register: resultado_job

    - name: Exibir ID do job lançado
      debug:
        msg: "Job ID lançado: {{ resultado_job.id }}"

    - name: Passar o job_id adiante no workflow
      set_stats:
        data:
          exec_job_id: "{{ resultado_job.id }}"
