---
- name: Launch a Job Template in Ansible Automation Controller
  hosts: localhost
  vars:
    job_template_name: Exec_Job_Template
    host_name:
  gather_facts: no
  tasks:
    - name: Launch Job Template
      ansible.controller.job_launch:
        job_template: "{{ job_template_name }}"
        extra_vars: "{{ extra_vars | default(omit) }}"
        limit: "{{ host_name | default(omit) }}"
