---
- name: Verificar carga da CPU e identificar maiores consumidores
  hosts: all
  gather_facts: true
  gather_subset:
    - all
  vars:
    load_threshold: 2.00

  tasks:

    - name: Verificar se ansible_loadavg está presente
      fail:
        msg: "O fato ansible_loadavg não está disponível neste host."
      when: ansible_facts.ansible_loadavg is not defined

    - name: Obter load average a partir dos facts
      set_fact:
        load_average: "{{ ansible_facts.ansible_loadavg[0] | float }}"

    - name: Comparar carga com limite
      set_fact:
        cpu_status: "{{ 'OK' if load_average < load_threshold else 'NOK' }}"
        cpu_message: >-
          {% if load_average < load_threshold %}
            Load abaixo do limite ({{ load_average }} < {{ load_threshold }})
          {% else %}
            Load acima do limite ({{ load_average }} >= {{ load_threshold }})
          {% endif %}

    - name: Mostrar status
      debug:
        msg: "Status: {{ cpu_status }} | Mensagem: {{ cpu_message }}"
