---
- name: Verificar carga da CPU usando facts
  hosts: all
  gather_facts: true
  vars:
    load_threshold: 2.00

  tasks:

    - name: Garantir que ansible_loadavg existe
      fail:
        msg: "O fato ansible_loadavg não está disponível."
      when: ansible_facts.ansible_loadavg is not defined

    - name: Definir carga média de 1 minuto
      set_fact:
        load_average: "{{ ansible_facts.ansible_loadavg['1m'] | float }}"

    - name: Comparar carga com limite
      set_fact:
        cpu_status: "{{ 'OK' if load_average < load_threshold else 'NOK' }}"
        cpu_message: >-
          {% if load_average < load_threshold %}
            Load abaixo do limite ({{ load_average }} < {{ load_threshold }})
          {% else %}
            Load acima do limite ({{ load_average }} >= {{ load_threshold }})
          {% endif %}

    - name: Mostrar status final
      debug:
        msg: "Status: {{ cpu_status }} | Mensagem: {{ cpu_message }}"
