---
- name: Coletar e exibir os facts do host
  hosts: all
  gather_facts: false  # desliga a coleta automática

  tasks:

    - name: Coletar todos os facts disponíveis
      ansible.builtin.setup:

    - name: Exibir todos os facts (com filtro opcional)
      debug:
        var: ansible_facts
