---
- name: Criar bucket S3 com Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: "us-east-2"
    s3_bucket_name: "meu-bucket-lab-ansible-{{ 9999 | random }}"
    obj_ownership: BucketOwnerEnforced
    
  tasks:
    - name: Criar bucket S3
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket_name }}"
        state: present
        object_ownership: "{{ obj_ownership }}"
        region: "{{ aws_region }}"
      register: bucket_result

